query getAllProducts($cursor: String, $limit: Int) {
  getAllProducts(limit: $limit, cursor: $cursor) {
    edges {
      node {
        id
        title
        handle
        description
        priceRange {
          min
          max
        }
        options {
          name
          values
        }
        featuredMedia {
          src
          thumbnailSrc
          id
          src
          type
        }
        media {
          edges {
            node {
              thumbnailSrc
              id
              src
              type
            }
          }
        }
        variants {
          edges {
            node {
              id
              title
              price
            }
          }
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
    }
  }
}
