query {
  getAllProducts {
    edges {
      node {
        id
        title
        handle
        description
        priceRange {
          min
        }
        featuredMedia {
          id
          src
          type
        }
      }
    }
  }
}
