query GetCollectByHandle($handle: String!) {
  getCollectionByHandle(handle: $handle) {
    id
    description
    handle
    title
    featuredMedia {
      id
      src
    }
    products {
      edges {
        node {
          id
          title
          handle
          description
          priceRange {
            min
            max
          }
          options {
            name
            values
          }
          featuredMedia {
            src
            thumbnailSrc
            id
            src
            type
          }
          media {
            edges {
              node {
                thumbnailSrc
                id
                src
                type
              }
            }
          }
          variants {
            edges {
              node {
                id
                title
                price
              }
            }
          }
        }
      }
    }
  }
}
