query GetPLPByHandle($handle: String!, $cursor: String, $limit: Int) {
  getCollectionByHandle(handle: $handle) @connection(key: "collection") {
    id
    description
    handle
    title
    featuredMedia {
      id
      src
    }
    products(limit: $limit, cursor: $cursor) @connection(key: "products") {
      edges {
        node {
          id
          title
          handle
          description
          productType
          tags
          vendor
          metafields {
            id
            namespace
            key
            value
          }
          priceRange {
            min
            max
          }
          options {
            name
            values
          }
          featuredMedia {
            src
            thumbnailSrc
            id
            src
            type
          }
          media {
            edges {
              node {
                thumbnailSrc
                id
                src
                type
              }
            }
          }
          variants {
            edges {
              node {
                id
                title
                price
                availableForSale
                selectedOptions {
                  name
                  value
                }
                swatchSrc
              }
            }
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
