query GetProductByHandle($handle: String!) {
  getProductByHandle(handle: $handle) {
    id
    title
    handle
    description
    priceRange {
      min
      max
    }
    featuredMedia {
      src
      thumbnailSrc
      id
      src
      type
    }
    media {
      edges {
        node {
          thumbnailSrc
          id
          src
          type
        }
      }
    }
    variants {
      edges {
        node {
          id
          title
          price
        }
      }
    }
  }
}
