query GetPageContentByHandle($handle: String!) {
  getBlogByHandle(handle: $handle) {
    id,
    handle,
    source,
    title,
    fields,
    collection {
      products {
        edges {
          node {
            id
            title
            handle
            description
            priceRange {
              min
              max
            }
            featuredMedia {
              src
              thumbnailSrc
              id
              src
              type
            }
            media {
              edges {
                node {
                  thumbnailSrc
                  id
                  src
                  type
                }
              }
            }
            variants {
              edges {
                node {
                  id
                  title
                  price
                }
              }
            }
          }
        }
      }
    },
    articles {
      edges {
        node {
          id,
          handle,
          source,
          title,
          description,
          tags,
          featuredMedia {
            id
            type,
            src
          },
          fields
        }
      }
    }
  }
}
